### PR TITLE
test correction set_env > GITHUB_ENV

### PR DESCRIPTION
**Pull request by G1K**
An alternative solution https://github.com/tete1030/openwrt-fastbuild-actions/issues/19 , but I don't like that I have to run commands in the container from root

### CODE REVIEW

**Comment by tete1030** [comment]
Hi, thanks for your help. Since I haven't been maintaining this repo for a while, I may have to find some time to check whether the current set-env method is sufficient. I see in your change the environment variables are only passed into containers, will they be also available outside containers? 

Also, why is it necessary to run from root? Is it for writing into `$GITHUB_ENV`? Probably can we just change the permission of the GITHUB_ENV file?

And I don't follow the QEMU part as well. Is it for building buildx?

**Comment by G1K** [comment]
I tried to change the permissions, but the GITHUB_ENV variable keeps changing and new files are created. And I managed to write only by mounting it inside. But the downside is that openwrt is not built as root. So I am using a workaround with ACTIONS_ALLOW_UNSECURE_COMMANDS, but it seems to be deprecated and disabled shortly

buildx - Yes, it is outdated and you get a warning

**Comment by tete1030** [comment]
Thanks.

**Comment by alpha7504** [comment]
> I tried to change the permissions, but the GITHUB_ENV variable keeps changing and new files are created. And I managed to write only by mounting it inside. But the downside is that openwrt is not built as root. So I am using a workaround with ACTIONS_ALLOW_UNSECURE_COMMANDS, but it seems to be deprecated and disabled shortly
> 
> buildx - Yes, it is outdated and you get a warning

Hello,

did you managed to fix this issue...? I've been trying to make it work, but the compilation always stops at tar compile, with the message "configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1" I set this in env in build-openwrt.yml but still it doesn't work.
I've long heard it's bad to compile as root... how to run docker as non-root user with root privileges..?

**Pull request merged**
